@echo off
echo Starting Option Seeker...
echo.
echo Starting Backend Server (FastAPI)...
start "Option Seeker Backend" cmd /k "cd /d %~dp0backend && py -3.14 -m uvicorn main:app --host 0.0.0.0 --port 8000"
echo.
echo Waiting for backend to start...
timeout /t 3 /nobreak > nul
echo.
echo Starting Frontend Server...
start "Option Seeker Frontend" cmd /k "cd /d %~dp0frontend && npm run dev -- --port 3000"
echo.
echo Both servers are starting...
echo Backend: http://localhost:8000
echo Frontend: http://localhost:3000
